name: GitHub Pages
on:
  push:
    branches: [master]
  workflow_dispatch:
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: npm install --ignore-scripts
      - name: Build
        run: npm run build
      - name: Add CNAME
        run: echo leveljs.org > dist/CNAME
      - name: Disable Jekyll
        run: touch dist/.nojekyll
      - name: List files
        run: ls -R dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
